---
- name: Update apt-get
  apt:
    update_cache: yes
- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Start Apache2
  service:
    name: apache2
    state: started
    enabled: yes